on:
  pull_request:
    branches:
      - bugfix/*
      - feature/*
      - hotfix/*
      - release

name: Jira Example

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Comment on issue
      uses: atlassian/gajira-comment@master
      with:
        issue: RKSA-1
        comment: "${{ github.event.pusher.name }} pushed to repository: ${{ github.event.repository.full_name }}"
