on:
  pull_request:
    branches:
      - bugfix/*
      - feature/*
      - hotfix/*
      - release

name: Jira Example

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Parse Jira Keys from Commit
      id: jira_keys
      if: always()
      uses: HighwayThree/jira-extract-issue-keys@master
      with:
        is-pull-request: ${{ github.event_name == 'pull_request' }}        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: print the issue id    
      run: echo ${{ github.event_name }}
        
    - name: Comment on issue
      uses: atlassian/gajira-comment@master
      with:
        issue: RKSA-1
        comment: "${{ github.event.pusher.name }} pushed to repository: ${{ github.event.repository.full_name }}"
        
    - uses: actions/checkout@v1
    - uses: 8BitJonny/gh-get-current-pr@1.4.0
      id: PR
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Verbose setting SHA when using Pull_Request event trigger to fix #16
        sha: ${{ github.event.pull_request.head.sha }}
        # Only return if PR is still open
        filterOutClosed: true
    - run: echo "Your PR is ${prNumber} and its JSON is ${prJSON}"
      if: success() && steps.PR.outputs.number
      env:
        prNumber: ${{ steps.PR.outputs.number }}
        # JSON object with the full PR object
        prJSON: ${{ steps.PR.outputs.pr }}
        # Direct access to common PR properties
        prUrl: ${{ steps.PR.outputs.pr_url }}
        prTitle: ${{ steps.PR.outputs.pr_title }}
        prBody: ${{ steps.PR.outputs.pr_body }}
        prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
        prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
        prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
        prLabel: ${{ steps.PR.outputs.pr_labels }}    
        
