on:
#   push:
#     branches:
#       - main
# #      - release
#   push:
#     branches:
#       - main
# ##      - release
  pull_request:
    branches:
      - bugfix/*
      - feature/*
      - hotfix/*
      - release

name: Jira Example

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Parse Jira Keys from Commit
      id: jira_keys
      if: always()
      uses: HighwayThree/jira-extract-issue-keys@master
      with:
        is-pull-request: ${{ github.event_name == 'pull_request' }}        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: print the issue id    
      run: echo ${{ github.event_name }}
        
    - name: Comment on issue
      uses: atlassian/gajira-comment@master
      with:
        issue: RKSA-1
        comment: "${{ github.event.pusher.name }} pushed to repository: ${{ github.event.repository.full_name }}"
